source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/IUCoco/LessonPrivatePodspecComponent.git'

use_frameworks!

target 'CZQLiveKit_Example' do
    pod 'CZQLiveKit', :path => '../'
    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
end
